#!/bin/zsh

cd book/epub

7z x 没有治不好的病.epub -o没有治不好的病 -y
mv 没有治不好的病.epub 没有治不好的病.bak.epub

cd 没有治不好的病

sed -i 's|idref="cover.html"|idref="cover.html" properties="duokan-page-fullscreen"|g' **/content.opf

sed -i 's|<p><img|<p style="text-align: center;"><img|g; 
    s|<p>|<p style="text-indent: 2em;">|g;
    s|<h1>|<h1 style="font-size: 1.5em;">|g;
    s|<h2>|<h2 style="font-size: 1.2em;">|g;
    s|<h3>|<h3 style="font-size: 1.1em;">|g;
    ' **/*.html

a ${PWD:t}.epub .

sed -i 's|.*cover\.html.*||g' **/content.opf

sed -i '12,17d' **/toc.ncx

a ${PWD:t}_to_pdf.epub .
