#!/bin/zsh

cd book/epub

7z x 没有治不好的病.epub -o没有治不好的病 -y
mv 没有治不好的病.epub 没有治不好的病.bak.epub

cd 没有治不好的病

sed -i 's|idref="cover.html"|idref="cover.html" properties="duokan-page-fullscreen"|g' **/content.opf

sed -i 's|<p><img|<p style="text-align: center;"><img|g' **/*.html

a ${PWD:t}.epub .
